Wrap types (if needed) before comparing or asserting.
impermeable/coq-waterproof pull request #60
Opened 2024-05-07 18:00 UTC by DikieDick

The goal of this PR is to add an utility function (called 'correct_type_by_wrapping') that fixes some issues regarding the types of (namely) boolean statements when comparing or asserting. 

Example:
```coq
Either (x = y) or (x != y).
```
Would not work before as the `x != y` term has type `bool` and needed to be wrapped in `is_true`.

This also causes problems when comparing the type of the statement `x != y` as done in `Since`, since the type of `x != y` is not 'Type', 'Set' or 'Prop'.

I have created the utility function `correct_type_by_wrapping` that 
1. Adds the 'is_true' wrapping to booleans.
2. Leaves 'Prop', 'Type' and 'Set' unchanged.
3. Throws an error if a statement with type other than 'bool', 'Prop', 'Type' or 'Set' is encountered.

Where necessary this function has been added to the tactics in the library.

### Changes:
- Added [`theories/Util/TypeCorrector.v`](theories/Util/TypeCorrector.v)
- Added [`tests/util/TypeCorrector.v`](tests/util/TypeCorrector.v)
- Added calls to `correct_type_by_wrapping` from `TypeConstructor` to Waterproof tactics where needed.

2024-05-09 07:58 UTC, jim-portegies requested changes
Thanks! Could you please add tests for the tactics you've modified, in the separate test files that are available for these tactics. E.g. for the Assume tactic, add a test to `tests/tactics/Assume.v`

Finally, could you please check locally if the compilation with this new branch has slowed down. I compiled twice and once was very slow, the second time was much faster.

```coq
Goal true -> (0 = 0).
Proof.
Assume (true).
Abort.
```

2024-05-09 07:58 UTC, jim-portegies commented on theories/Util/TypeCorrector.v
> +      of_string "Expected a term with type in ['Prop', 'Set', 'Type', 'bool'], but we got a term of type '";
```suggestion
      of_string "Expected a term with type in ['Prop', 'Set', 'Type', 'bool'], but got a term of type '";
```

2024-05-09 07:58 UTC, jim-portegies commented on theories/Util/TypeCorrector.v
> +  end.
Please add a newline at the end of the file

2024-05-09 07:58 UTC, jim-portegies commented on tests/util/TypeCorrector.v
> +End assert_tests.
Please add a new line to the end of the file

2024-05-09 16:39 UTC, DikieDick commented on tests/util/TypeCorrector.v
> +End assert_tests.
Fixed in 6349b70c6cb4081f9aa7c60e0f5af88dcb3fc136

2024-05-09 16:39 UTC, DikieDick commented on theories/Util/TypeCorrector.v
> +  end.
Fixed in https://github.com/impermeable/coq-waterproof/pull/60/commits/6349b70c6cb4081f9aa7c60e0f5af88dcb3fc136

2024-05-09 17:43 UTC, DikieDick commented
> Finally, could you please check locally if the compilation with this new branch has slowed down. I compiled twice and once was very slow, the second time was much faster.

I have not noticed any slowdowns in my development. Running `hyperfine` to test on 10 compilation runs (`dune clean; dune build`) gave the following:
| Branch | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `main` | 38.648 ± 1.035 | 37.676 | 41.229 | 1.01 ± 0.03 |
| `TypeCorrector` | 38.347 ± 0.599 | 37.398 | 39.339 | 1.00 |

2024-05-11 05:59 UTC, jim-portegies requested changes
Thanks a lot for the new tests and the experiments on timing!

A few suggestions, mostly for extra tests. Please see if you agree.

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/ItSuffices.v
> +Goal B.
```suggestion
Goal ((is_true b) -> B) -> B.
```

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/ItSuffices.v
> +  admit.
```suggestion
  intro H.
```
(I prefer to have no 'admits' in the test code).

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/ItSuffices.v
> +Goal B.
```suggestion
Goal ((is_true b) -> B) -> B.
```

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/ItSuffices.v
> +  admit.
```suggestion
  intro H.
```

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/ToShow.v
> +Abort.
```suggestion
Abort.

(* Test 13: "It suffices" works with boolean statement and boolean "Since"
  clause *)
Goal ((is_true b) -> B) -> B.
Proof.
  intro H.
  It holds that (true).
  Since (true) it suffices to show that (b).
Abort.
```

2024-05-11 05:59 UTC, jim-portegies commented on tests/tactics/Conclusion.v
> +Qed.
```suggestion
Qed.

(** * Test 10
  Test whether the conclude tactic can handle a boolean statement
  with boolean since-clause.
*)
Goal (is_true true).
Proof.
It holds that (true).
Since (true) we conclude that (true).
Qed.
```

2024-05-11 09:52 UTC, DikieDick commented on tests/tactics/Conclusion.v
> +Qed.
I have updated the indentation within the proof.

2024-05-11 09:54 UTC, DikieDick commented on tests/tactics/ToShow.v
> +Abort.
Shouldn't this test be in [tests/tactics/ItSuffices.v](https://github.com/impermeable/coq-waterproof/pull/60/files/6349b70c6cb4081f9aa7c60e0f5af88dcb3fc136..53ebd63676b16a91cd02c40d7885fa49d279090a#diff-1decd7f86695d790236cfebead876a4fac168e01b886a136384a1e7d2fc896b4)?

2024-05-11 10:52 UTC, jim-portegies commented on tests/tactics/ToShow.v
> +Abort.
Yes I'm sorry!

2024-05-18 03:39 UTC, jim-portegies approved these changes

2024-05-18 03:40 UTC, merged